resources:
  - name: runpopprop
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines: 
  - name: TRIGGER
    steps:
      - name: TRIGGER
        type: Bash
        configuration:
          outputResources:
            - name: runpopprop
        execution:
          onExecute:
            - write_output runpopprop runId=$run_number
  - name: TRIGGER_OUT_1
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv




