resources:
  - name: runpopprop
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpoppropin
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpoppropin1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpopprop2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpopprop3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines: 
  - name: TRIGGER_IN_1_1
    steps:
      - name: TRIGGER_IN
        type: Bash
        configuration:
          outputResources:
            - name: runpoppropin1
        execution:
          onExecute:
            - echo "writing output"
            - write_output runpoppropin1 runNumber=${run_number}
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_IN
    steps:
      - name: TRIGGER_IN
        type: Bash
        configuration:
          outputResources:
            - name: runpoppropin
          inputResources:
            - name: runpoppropin1
        execution:
          onExecute:
            - echo "asd"
            - write_output runpoppropin runNumber=${run_number}
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_IN_1
    steps:
      - name: TRIGGER_IN
        type: Bash
        configuration:
          outputResources:
            - name: runpoppropin
        execution:
          onExecute:
            - echo "asd"
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_1
    steps:
      - name: TRIGGER_IN
        type: Bash
        configuration:
          outputResources:
            - name: runpopprop
        execution:
          onExecute:
            - echo "asd"
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER
    steps:
      - name: TRIGGER
        type: Bash
        configuration:
          outputResources:
            - name: runpopprop
          inputResources:
            - name: runpoppropin
        execution:
          onExecute:
            - write_output runpopprop runId=$run_number
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_1_1
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop3
        execution:
          onExecute:
            - printenv
            - write_output runpopprop3 runNumber=${run_number}
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_3_3
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop3
        execution:
          onExecute:
            - printenv
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_1_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_1_3
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_1_4
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
            - write_output runpopprop2 runNumber=${run_number}
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_3_1
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
            - set_run_name "V${run_number}.0.0"
  - name: TRIGGER_OUT_3_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
            - set_run_name "V${run_number}.0.0"




